// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGames() {
  return window['go']['bindings']['App']['GetGames']();
}

export function HashServerSeed(arg1) {
  return window['go']['bindings']['App']['HashServerSeed'](arg1);
}

export function StartScan(arg1) {
  return window['go']['bindings']['App']['StartScan'](arg1);
}
