// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {games} from '../models';
import {store} from '../models';
import {bindings} from '../models';

export function CancelRun(arg1:string):Promise<void>;

export function GetGames():Promise<Array<games.GameSpec>>;

export function GetRun(arg1:string):Promise<store.Run>;

export function GetRunHits(arg1:string,arg2:number,arg3:number):Promise<bindings.HitsPage>;

export function HashServerSeed(arg1:string):Promise<string>;

export function ListRuns(arg1:bindings.RunsQuery):Promise<bindings.RunsList>;

export function StartScan(arg1:bindings.ScanRequest):Promise<bindings.ScanResult>;
