// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {games} from '../models';
import {store} from '../models';
import {bindings} from '../models';
import {context} from '../models';

export function CancelRun(arg1:string):Promise<void>;

export function ExportRunCSV(arg1:string):Promise<string>;

export function GetGames():Promise<Array<games.GameSpec>>;

export function GetKenoRisks():Promise<Array<string>>;

export function GetRun(arg1:string):Promise<store.Run>;

export function GetRunHits(arg1:string,arg2:number,arg3:number):Promise<bindings.HitsPage>;

export function GetSeedRuns(arg1:string):Promise<bindings.SeedRunGroup>;

export function HashServerSeed(arg1:string):Promise<string>;

export function ListRuns(arg1:bindings.RunsQuery):Promise<bindings.RunsList>;

export function StartKenoB2BScan(arg1:bindings.KenoB2BRequest):Promise<bindings.KenoB2BResult>;

export function StartScan(arg1:bindings.ScanRequest):Promise<bindings.ScanResult>;

export function Startup(arg1:context.Context):Promise<void>;
