// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRun(arg1) {
  return window['go']['bindings']['App']['CancelRun'](arg1);
}

export function GetGames() {
  return window['go']['bindings']['App']['GetGames']();
}

export function GetRun(arg1) {
  return window['go']['bindings']['App']['GetRun'](arg1);
}

export function GetSeedRuns(arg1) {
  return window['go']['bindings']['App']['GetSeedRuns'](arg1);
}

export function GetRunHits(arg1, arg2, arg3) {
  return window['go']['bindings']['App']['GetRunHits'](arg1, arg2, arg3);
}

export function HashServerSeed(arg1) {
  return window['go']['bindings']['App']['HashServerSeed'](arg1);
}

export function ListRuns(arg1) {
  return window['go']['bindings']['App']['ListRuns'](arg1);
}

export function StartScan(arg1) {
  return window['go']['bindings']['App']['StartScan'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['App']['Startup'](arg1);
}
