// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScriptLog() {
  return window['go']['bindings']['ScriptModule']['GetScriptLog']();
}

export function GetScriptState() {
  return window['go']['bindings']['ScriptModule']['GetScriptState']();
}

export function StartScript(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['ScriptModule']['StartScript'](arg1, arg2, arg3, arg4);
}

export function Startup(arg1) {
  return window['go']['bindings']['ScriptModule']['Startup'](arg1);
}

export function StopScript() {
  return window['go']['bindings']['ScriptModule']['StopScript']();
}
