// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scripting} from '../models';
import {bindings} from '../models';
import {context} from '../models';

export function GetScriptLog():Promise<Array<scripting.LogEntry>>;

export function GetScriptState():Promise<bindings.ScriptState>;

export function StartScript(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopScript():Promise<void>;
