// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Client() {
  return window['go']['bindings']['SessionModule']['Client']();
}

export function Disconnect() {
  return window['go']['bindings']['SessionModule']['Disconnect']();
}

export function GetSessionStatus() {
  return window['go']['bindings']['SessionModule']['GetSessionStatus']();
}

export function IsConnected() {
  return window['go']['bindings']['SessionModule']['IsConnected']();
}

export function SetCurrency(arg1) {
  return window['go']['bindings']['SessionModule']['SetCurrency'](arg1);
}

export function SetSessionToken(arg1, arg2, arg3) {
  return window['go']['bindings']['SessionModule']['SetSessionToken'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['bindings']['SessionModule']['Startup'](arg1);
}
