// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stake} from '../models';
import {bindings} from '../models';
import {context} from '../models';

export function Client():Promise<stake.Client>;

export function Disconnect():Promise<void>;

export function GetSessionStatus():Promise<bindings.SessionStatus>;

export function IsConnected():Promise<boolean>;

export function SetCurrency(arg1:string):Promise<void>;

export function SetSessionToken(arg1:string,arg2:string,arg3:string):Promise<bindings.SessionStatus>;

export function Startup(arg1:context.Context):Promise<void>;
